export const mockInstructors = [
    {
        id: "1",
        name: "Olivia Rhye",
        email: "olivia@example.com",
        phone: "+1234567890",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 2000,
        industry: "Product Designer",
        videos: 2,
        bio: "Olivia is a passionate product designer with over 8 years of experience creating intuitive and user-friendly interfaces. She specializes in UX research, wireframing, and prototyping, with a focus on educational platforms.",
        expertise: ["UI/UX Design", "Figma", "User Research", "Design Systems"],
    },
    {
        id: "2",
        name: "Phoenix Baker",
        email: "phoenix@example.com",
        phone: "+1234567891",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 3000,
        industry: "Product Manager",
        videos: 3,
        bio: "Phoenix is a seasoned product manager who has led teams at several tech startups. With a background in both business and technology, she brings a unique perspective to product development and strategy.",
        expertise: ["Product Strategy", "Agile", "User Stories", "Roadmapping"],
    },
    {
        id: "3",
        name: "Lana Steiner",
        email: "lana@example.com",
        phone: "+1234567892",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 150,
        industry: "Frontend Developer",
        videos: 7,
        bio: "Lana is a frontend developer with expertise in modern JavaScript frameworks. She loves creating responsive, accessible web applications and sharing her knowledge with students around the world.",
        expertise: ["React", "JavaScript", "CSS", "Responsive Design"],
    },
    {
        id: "4",
        name: "Demi Wilkinson",
        email: "demi@example.com",
        phone: "+1234567893",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 20,
        industry: "Backend Developer",
        videos: 1,
        bio: "Demi specializes in backend development with a focus on scalable architecture and database design. She has worked on high-traffic applications and enjoys teaching the fundamentals of server-side programming.",
        expertise: ["Node.js", "Python", "Databases", "API Design"],
    },
    {
        id: "5",
        name: "Candice Wu",
        email: "candice@example.com",
        phone: "+1234567894",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 1500,
        industry: "Fullstack Developer",
        videos: 10,
        bio: "Candice is a fullstack developer with experience across the entire development stack. She specializes in building complete web applications from concept to deployment, with a passion for teaching practical coding skills.",
        expertise: ["JavaScript", "React", "Node.js", "MongoDB", "AWS"],
    },
    {
        id: "6",
        name: "Natali Craig",
        email: "natali@example.com",
        phone: "+1234567895",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 250,
        industry: "UX Designer",
        videos: 2,
        bio: "Natali is a UX designer focused on creating intuitive digital experiences. With a background in psychology, she brings a deep understanding of user behavior to her design process and teaching approach.",
        expertise: ["User Research", "Wireframing", "Prototyping", "Usability Testing"],
    },
    {
        id: "7",
        name: "Drew Cano",
        email: "drew@example.com",
        phone: "+1234567896",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 40,
        industry: "UX Copywriter",
        videos: 2,
        bio: "Drew is a UX copywriter who specializes in creating clear, concise, and compelling content for digital products. He helps teams communicate effectively with users through thoughtful microcopy and content strategy.",
        expertise: ["UX Writing", "Content Strategy", "Microcopy", "Brand Voice"],
    },
    {
        id: "8",
        name: "Orlando Diggs",
        email: "orlando@example.com",
        phone: "+1234567897",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 1200,
        industry: "UI Designer",
        videos: 2,
        bio: "Orlando is a UI designer with a strong background in visual design and branding. He creates beautiful, functional interfaces that balance aesthetics with usability, and enjoys teaching design principles to students.",
        expertise: ["Visual Design", "Design Systems", "Typography", "Color Theory"],
    },
    {
        id: "9",
        name: "Andi Lane",
        email: "andi@example.com",
        phone: "+1234567898",
        avatar: "/placeholder.svg?height=32&width=32",
        views: 800,
        industry: "Product Manager",
        videos: 3,
        bio: "Andi is a product manager with experience in both B2B and B2C products. She excels at understanding user needs and translating them into product requirements, with a focus on data-driven decision making.",
        expertise: ["Product Strategy", "User Research", "Analytics", "A/B Testing"],
    },
]

